# Generated by Django 6.0.2 on 2026-02-12 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppUser',
            fields=[
                ('user_id', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=128)),
                ('role', models.CharField(choices=[('admin', 'admin'), ('moderator', 'moderator'), ('user', 'user')], max_length=20)),
            ],
        ),
    ]
